server:
  port: 8080
  # servlet:
  #   context-path: /
  #   encoding:
  #     charset: UTF-8
  #     enabled: true
  #     force: true

spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/marrydb
    # platform: postgres
    username: marry
    password: 1234
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    # properties:
    # hibernate:
    # format-sql: true
    # dialect: org.hibernate.dialect.PosterSQLDialect
    show-sql: true
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # open-in-view: false
    # generate-ddl: true

springdoc:
  packages-to-scan: com.colabear754.springdoc_example.controllers
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha