server:
  port: 8080
  # servlet:
  #   context-path: /
  #   encoding:
  #     charset: UTF-8
  #     enabled: true
  #     force: true

spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: ${SPRING_DATASOURCE_URL}
    # username: ${SPRING_DATASOURCE_USERNAME}
    # password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://localhost:5432/marrydb?autoReconnect=true
    username: marry
    password: 1234
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    # properties:
    # hibernate:
    # format-sql: true
    # dialect: org.hibernate.dialect.PosterSQLDialect
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

springdoc:
  packages-to-scan: com.jnhn.webService
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: api/
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
